Meson: Add workaround for a glib-2.0 (< 2.67.1) internal bug
Since glib-2.0( < 2.67.1) has a bug that incurs a warning,
incompatible-pointer-types, on gcc (>= 11) as follows:

/usr/include/glib-2.0/glib/gatomic.h:112:5: error: argument 2 of ‘__atomic_load’ discards ‘volatile’ qualifier [-Werror=incompatible-pointer-types]
  112 |     __atomic_load (gapg_temp_atomic, &gapg_temp_newval, __ATOMIC_SEQ_CST);   \
      |     ^~~~~~~~~~~~~
This patch adds a workaround for this bug to the meson build script.

Signed-off-by: Wook Song <wook16.song@samsung.com>